### ISSUE TITLE
Windows: Go through AppVeyor build logs, find warnings and address them properly

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#131]
Help welcome!
https://ci.appveyor.com/project/hartwork/libexpat/history

**Comment by vanklompf** [comment]
Most of the Visual warnings are due to usage unsecure string functions (strcpy vs strcpy_s, strlen vs strlen_s). Do You rather prefer refactoring code for all platforms or just tuning warning level?

**Comment by hartwork** [comment]
For the unsafe string warnings I think I'd prefer silencing (just) that class.

**Comment by vanklompf** [comment]
Ok, I can see that "secure" warnings are silenced in cmake builds but not in provided Visual Solution file (sln). I will silence also in SLN and work on other, more significant warnings on AppVeyor.

**Comment by hartwork** [comment]
The way I understood https://github.com/libexpat/libexpat/blob/master/appveyor.yml#L164 the Visual Studio files used with AppVeyor are generated on the fly by CMake. To me that means that the CMake way does not yet silence unsecure function warnings, effectively.

**Comment by vanklompf** [comment]
CMake has set proper option to silence those warnings [https://github.com/libexpat/libexpat/blob/86cbbb2e748fc1c444aa3083ef07e8f0772f3983/expat/CMakeLists.txt#L83](here)

There are also VC project files hosted on git repo. I am not sure what is there purpose as they are duplicating CMake. Probably they are useful to browse source code easily, without need of generating project files using CMake. On the other hand they are little misleading, because build output using provided projects is different than using proper CMake generated projects.

**Comment by hartwork** [comment]
> On the other hand they are little misleading, because build output using provided projects is different than using proper CMake generated projects.

@kwaclaw if we dropped expat.sln and friends, would auto-generated project files using CMake like https://github.com/libexpat/libexpat/blob/master/appveyor.yml#L164 be good enough for future Windows release binaries as-is? What adjustments would you need?
