### ISSUE TITLE
Unable to ./configure on Ubuntu

### ISSUE THREAD

**Issue by tpmccallum** [libexpat/libexpat#20]
Downloaded the zip from https://github.com/libexpat/libexpat/archive/master.zip
Extracted and tried ./configure in the libexpat-master/expat directory but got the following error
```
config.status: error: cannot find input file: `expat_config.h.in'
```

**Comment by hartwork** [comment]
Hi Timothy,

how did you generate the configure script? Did you do anything different to this?:
```
wget https://github.com/libexpat/libexpat/archive/master.zip
unzip master.zip
cd libexpat-master/expat
./buildconf.sh
./configure
```

Best, Sebastian

**Comment by tpmccallum** [comment]
Hi Sebastian,
Thanks for your speedy reply.
I seem to have this sorted now. I am using the following commands to install libexpat

cd ~
unzip Downloads/libexpat-master.zip
cd libexpat-master/expat
cmake .
make -j 2
sudo make install

Is this method of installation satisfactory? I am happy to be guided by you in relation to best practice ... eg creating a build dir rather than running from the root dir etc. Thoughts?

Kind regards
Tim

**Comment by hartwork** [comment]
Hey!

I'm unsure what you want to achieve. `sudo make install` looks like a system-wide installation. Are you trying to replace/override libexpat of your Linux distro by something as new as Git `HEAD`? How to do that right and best may depend on the specific distro, their packaging and patching. 

So the `config.status: error: cannot find input file: `expat_config.h.in'` above turned out a usage non-bug thing?

**Comment by tpmccallum** [comment]
Hi,
Correct, just a usage issue and not a bug.
Sorry for the inconvenience.
Tim
