### ISSUE TITLE
Missing check for presence of stdint.h - does not compile with Solaris 8

### ISSUE THREAD

**Issue by gvzdus** [libexpat/libexpat#234]
Solaris 10 might not be the #1 OS any more, but I have some old servers... It lacks stdint.h, which is also recognized by configure.

However, in lib/siphash.h, stdint.h is included without the check for HAVE_STDINT_H

This works for me and compiles, I don't know if it is elegant:

#if defined(_WIN32) && defined(_MSC_VER) && (_MSC_VER < 1600)
  /* For vs2003/7.1 up to vs2008/9.0; _MSC_VER 1600 is vs2010/10.0 */
  typedef unsigned __int8   uint8_t;
  typedef unsigned __int32 uint32_t;
  typedef unsigned __int64 uint64_t;
#else
**#ifdef HAVE_STDINT_H**
#include <stdint.h> /* uint64_t uint32_t uint8_t */
**#endif**
#endif

**Comment by hartwork** [comment]
Hi! If it magically works without `stdint.h` then some other header is defining `uint64_t` and friends, I suppose. Could you research and share it's name? So we don't break things later without noticing.

**Comment by gvzdus** [comment]
Hi Sebastian,

I searched a bit using the following test program with the same includes as lib/xmlparse.c for Unix:

#include <stddef.h>
#include <string.h>                     /* memset(), memcpy() */
#include <assert.h>
#include <limits.h>                     /* UINT_MAX */
#include <stdio.h>                      /* fprintf */
#include <stdlib.h>                     /* getenv */
 
// #include <sys/time.h>                   /* gettimeofday() */  Positive
// #include <sys/types.h>                  /* getpid() */  Positive
// #include <unistd.h>                     /* getpid() */  Positive
// #include <fcntl.h>                      /* O_RDONLY */  Positive
#include <errno.h>
 
int main(int argc, char **argv) {
  uint8_t value = 0;
  uint64_t val64 =0;
  return (int) value + val64;
}

Activating *any* of the includes marked with „Positive“ included the definition of uint8_t & uint64_t and made
the program compile.

This is why it compiles with not including stdint.h

Anyway, I think the suggested patch should never break something, because if stdint.h is not present (and
configure tested for that), including the non-existent file is guaranteed to fail…

Best regards,


Georg

**Comment by marcomaggi** [comment]
@gvzdus, you should be able to find the defining header file by issuing:
```
grep uint8_t /usr/include/*.h | grep typedef
```
or:
```
grep uint8_t /usr/include/*.h | grep define
```
or similar commands.  There should be a "root" header file that defines these types.

**Comment by gvzdus** [comment]
Hi,

they are defined in sys/int_types.h

which is included by

sys/inttypes.h
sys/regset.h
sys/synch.h
sys/types.h
sys/types32.h

Well, I took that approach, but at that level I gave up searching the path down to any of these files…

Best regards, Georg

**Comment by gvzdus** [comment]
Btw:

I have to admit: 
It is Solaris 8 which does not have stdint.h.
Solaris 10 has stdint.h, which then includes sys/int_types.h, having the definitions.

The reason of my „sudden interest“ in expat is that recent apr_util removed its
own included version of expat, so I have to compile by myself…

So everybody building Apache httpd (which builds more / less fine with Solaris 8)
has also to compile expat.

Best regards, 


Georg

**Comment by marcomaggi** [comment]
So `configure.ac` can check for `stdint.h`, `inttypes.h`, `sys/inttypes.h` and then use the macros:

```
AC_TYPE_UINT8_T
AC_TYPE_UINT32_T
AC_TYPE_UINT64_T
```

**Comment by hartwork** [comment]
@gvzdus ,

please give commit d72d5852dbac176abd15c6ee1ee90ff5b33bfe83 on branch `issue-234-missing-stdint-h` a try, e.g. like this:
```console
# git clone --branch issue-234-missing-stdint-h --depth 1 https://github.com/libexpat/libexpat.git
# cd libexpat/expat/
# ./buildconf.sh && ./configure --without-tests --without-docbook --without-xmlwf --without-examples && make                   
```
Please report back how that goes.

I should add that Expat officially requires a C99 compiler since 2.2.2 (2017-07-12) which in turn is required to provide fixed integer types from `stdint.h`. So if Solaris 8 does not have a C99 compiler, it's officially unsupported. `AC_TYPE_UINT8_T` seems nice for pre-C99 compilers.

Also please note that I try to keep `siphash.h` work for standalone copy paste to other projects, hence I try not to introduce a hard dependency on `HAVE_` things in that file.

Please report back how that patch works for you. Thanks!

**Comment by noloader** [comment]
Expat might also consider a [GCC Compile Farm](https://cfarm.tetaneutral.net/) account. The project is eligible for a free account because it is an open source project.

The CFarm gives you access to a lot of different hardware, OSes, and compilers, including Solaris 9, 10 and 11. You can also test on big-endian PowerPC's running AIX.

Mailing list at [cfarm-users](https://lists.tetaneutral.net/listinfo/cfarm-users).

**Comment by david-loffredo** [comment]
I don't think this issue is valid anymore.   I have built the current master on Solaris 10 SPARC, with Developer Studio 12.6, for 32bit, 64bit (-m64) and PIC.    I am working on an embedded project, and don't have autoconf or cmake in that environment, so I use a manual expat_config with the following, and no problems with any includes.

```
/*============================================================*/
#ifdef __sun
#define HAVE_MEMMOVE

/* Solaris sparc is big endian, x86 is little endian */
#ifdef __sparc
#define BYTEORDER 4321
#define WORDS_BIGENDIAN 1
#else
// i386 is defined when compiling 32bit code only, the others for 64bit
#if defined(__i386) || defined (__amd64) || defined(__x86_64)
#define BYTEORDER 1234
#else
#error Unknown processor type
#endif
#endif

/* solaris 11.3 should have the getrandom system call */
/* solaris 10 has /dev/urandom */
#define XML_DEV_URANDOM

#endif /* solaris */
```

Sun Studio 12 32bit

/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I.  xmlparse.c
/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I.  xmlrole.c
/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I.  xmltok.c

Sun Studio 12 with -KPIC -mt

/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -KPIC -mt xmlparse.c
/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -KPIC -mt xmlrole.c
/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -KPIC -mt xmltok.c


Sun Studio 12 64bit code

/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -m64 xmlparse.c
/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -m64 xmlrole.c
/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -m64 xmltok.c


Sun Studio 12 64bit -KPIC -mt

/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -m64 -KPIC -mt xmlparse.c
/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -m64 -KPIC -mt xmlrole.c
/opt/developerstudio12.6/bin/cc -c -O  -DHAVE_EXPAT_CONFIG_H -I. -m64 -KPIC -mt xmltok.c

**Comment by hartwork** [comment]
Closing as obsolete
