### ISSUE TITLE
Windows:  rand_s() instead of loadlibrary convolution?

### ISSUE THREAD

**Issue by david-loffredo** [libexpat/libexpat#299]
Is there a specific reason that the current implementation does not just use the published rand_s() API call (which uses RtlGenRandom) and instead rolls its own dynamic library load to call RtlGenRandom?

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand-s?view=vs-2019

EDIT: I'd be happy to submit a patch, because I think it would simplify things quite a bit.

**Comment by hartwork** [comment]
Hi David,

I was not aware of `rand_s` at the time and `RtlGenRandom` was recommend and used elsewhere back then. While allowing us to drop `_Expat_LoadLibrary`, `rand_s` is not as flexible as `RtlGenRandom` as it writes `sizeof(unsigned int)` bytes rather than an arbitrary number like `RtlGenRandom`. We need `sizeof(unsigned long)` bytes already and may use more in the future (see #47). So we'd need a loop around `rand_s` and get that waterproof. So far I'm not sold on the cost-gain-ratio here. What's the core gain you see?

Best, Sebastian

**Comment by david-loffredo** [comment]
The core gain is simplification.    loadlibrary.c is not core to expat functionality and has tests for individual KB and system path issues that you must now maintain across future Windows versions.    The "SystemFunction036" entry point has remained stable so far, but is definitely a step below a proper API.   You encourage people to not bundle expat #44, this is similar encouragement not to bundle OS functionality.

As for the use, on win32 and win64, sizeof(unsigned int) is the same as sizeof(unsigned long) at four bytes, so only one call is currently needed.    If you want to leverage more bytes, I will just point out that writeRandomBytes_arc4random is the exact solution substituting arc4random() with rand_s()

**Comment by hartwork** [comment]
What about `rand_s` MinGW support?

**Comment by hartwork** [comment]
(Closing was without purpose and from a mis-placed click.)

You have good arguments here but the current solution seems to work, I expect it to continue to work for a while more, and testing new Windows code is not easy to to do for me personally and not without risk of breaking things. So I'm a little shy about this change. I also wonder about ways to avoid code duplication from `writeRandomBytes_arc4random` that the C prep-processor would allow without getting things too dirty.

For MinGW I found https://github.com/mirror/mingw-w64/commit/b73911e89a3a4ac19948a608c056c007e20d5c32#diff-048ec53407584f33e6a2c0f9b7129ec5 but I'm not fully sure of it's implications.

**Comment by david-loffredo** [comment]
You raised a good question -- I just checked both mingw and mingw-x64.    

The original mingw does not appear to be under active development (installer is copyright 2013), and is still shipping an expat 2.1.0 DLL.   It is a 32bit only package and does not have rand_s.

The mingw-x64 is under active development, has 32 and 64bit builds, and does have rand_s() declared in stdlib.h the same as the nominal MS version.   

```
#ifdef _CRT_RAND_S
  _SECIMP errno_t __cdecl rand_s(unsigned int *randomValue);
#endif
```

**Comment by hartwork** [comment]
How about a test balloon pull request that just does two tiny things and see what we get from the CI — both Travis and AppVeyor:
- Add `#define _CRT_RAND_S` and `#include <stdlib.h>`
- Add a dummy call to `rand_s` in the right place.

After that I imagine we might know if it's worth a full integration and replacing `LoadLibrary`. Should I give that a try or would you want to do it yourself? I'm fine either way.

**Comment by david-loffredo** [comment]
Sure, I'll try to put that together this week.

**Comment by hartwork** [comment]
Cool!

**Comment by david-loffredo** [comment]
See pull request #302

**Comment by vadz** [comment]
Just a note: I've tested the build of Expat 2.2.8 as included in wxWidgets with the latest MinGW 8.2 gcc version and it gives us the expected (because, as [a previous comment](https://github.com/libexpat/libexpat/issues/299#issuecomment-517826396) says, it's nowhere to be found in MinGW headers) warning:

```
../../src/expat/expat/lib/xmlparse.c: In function 'writeRandomBytes_rand_s':
../../src/expat/expat/lib/xmlparse.c:751:9: warning: implicit declaration of function 'rand_s'; did you mean 'rand'? [-Wimplicit-function-declaration]
     if (rand_s(&random32))
         ^~~~~~
         rand
```

But it still manages to link successfully because the function is present in `msvcrt.dll`. So we could do something like

```diff
diff --git a/expat/lib/xmlparse.c b/expat/lib/xmlparse.c
index 3236cb0..5445650 100644
--- a/expat/lib/xmlparse.c
+++ b/expat/lib/xmlparse.c
@@ -736,6 +736,13 @@ writeRandomBytes_arc4random(void *target, size_t count) {
 
 #ifdef _WIN32
 
+/* Provide declaration of rand_s() for MinGW-32 (not 64, which has it),
+   as it doesn't declare it in its header up to at least 5.2.2 version
+   of its runtime. */
+#if defined(__MINGW32__) && !defined(__MINGW64_VERSION_MAJOR)
+__declspec(dllimport) int rand_s(unsigned int*);
+#endif
+
 /* Obtain entropy on Windows using the rand_s() function which
  * generates cryptographically secure random numbers.  Internally it
  * uses RtlGenRandom API which is present in Windows XP and later.
```

to avoid the warning. I could submit this change as a PR, if this could be useful, of course.

**Comment by hartwork** [comment]
Hi @vadz , I guess we previously mis-assumed MinGW(32) to be dead then. We can add a prototype to address the warning but the prototype you propose does not seem to match https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand-s?view=vs-2019 yet. Looking forward to your pull request.

**Comment by vadz** [comment]
Thanks for your reply! I'll make a PR in a moment.

To be honest, I don't know what's going on with MinGW-32 myself. There doesn't seem to be any recent updates on their web page, and their installer seems to be stuck in 2017, but they do have pretty recent gcc 8.2 packages available for download and they seem to work well, so I've just decided to test them before our own release.

As for the prototype, I didn't use `errno_t` because MinGW doesn't have this neither. But `errno_t` is just a typedef for `int` in uCRT and, being part of the ABI, I don't think it's going to change in the foreseeable future.

**Comment by hartwork** [comment]
Alright!

**Comment by noloader** [comment]
Forgive me for stepping in on an older report... Should there simply be an Autotools test for `rand_s` and MinGW32?

```
AC_MSG_CHECKING([for arc4random (BSD, macOS or libbsd)])
AC_LINK_IFELSE([AC_LANG_SOURCE([
    #define _CRT_RAND_S 1
    #include <stdlib.h>
    void main(void) {
       unsigned int v;
       (void)rand_s(&v);
    }
  ])],
  [AC_DEFINE([HAVE_RAND_S], [1], [Define to 1 if you have the `rand_s' function.])
   AC_MSG_RESULT([yes])],
  [AC_MSG_RESULT([no])
])
```

And then something like:

```
#if defined(HAVE_RAND_S)
  #define _CRT_RAND_S 1
  #include <stdlib.h>
#endif
#if defined(__MINGW32__) && defined(HAVE_RAND_S)
  __declspec(dllimport) errno_t rand_s(unsigned int*);
#endif
```

**Comment by vadz** [comment]
Yes, the changes in #372 could be replaced with a configure test. I mostly did it like this just because there already were existing similar tests.

**Comment by hartwork** [comment]
@noloader Expat requires `rand_s` on Windows so the compilation and/or linking will fail if absent, right? Why do we need another check for configure then? The `HAVE_RAND_S` block above does not seem to have MSVC compilers in mind.

In general, if there is more to do on this front, please open dedicated tickets. Right here, things can only get lost, not ideal.
