### ISSUE TITLE
Do not install expat_config.h

### ISSUE THREAD

**Issue by repagh** [libexpat/libexpat#344]
expat_config.h is installed. This file is only used in expat source files, and not needed anywhere else. Installation seems not necessary, since it is not used by any installed expat headers, or any others for that matter. 

Why the issue? Just hit this on compiling simgear with its local expat for debugging purposes; the compile picked up the expat_config.h installed in  /opt/local/include (macports installation).

**Comment by hartwork** [comment]
Hi Rene,

it's unfortunate that the wrong `expat_config.h` is picked up.
I would expect that's an issue with order/list of include directories,
either in Expat's onw build system or in the way that it's called.
Is this about CMake or GNU Autotools?

(Our primary build system — GNU autotools — has been installing `expat_config.h` for years and CMake has been made to do the same in 2.2.8 now because it will become the primary and only build system in the near future.  So installation of `expat_config.h` is not something new, just for the record.)

Now if we actually stopped installing `expat_config.h`, that would break any application or `configure` script that does `#include <expat_config.h>` to e.g. check for DTD support (by checking for defined `XML_DTD`) at compile time.  Any ideas what to do about that problem?

Best, Sebastian

----
Some additional info about our `XML_*` build flags:

These no *not* affect public API:
- `XML_CONTEXT_BYTES`
- (`XML_DEV_URANDOM`)
- `XML_DTD`
- `XML_MIN_SIZE`
- `XML_NS`

These *do* affect public API:
- `XML_ATTR_INFO`
- `XML_LARGE_SIZE`
- `XML_UNICODE`
- `XML_UNICODE_WCHAR_T`

Out of those, `XML_UNICODE` and `XML_UNICODE_WCHAR_T` and `XML_LARGE_SIZE` change the API, and `XML_ATTR_INFO` adds to the API.

At least `XML_UNICODE` and `XML_UNICODE_WCHAR_T` are known to be used from application code so `expat.h` needs to be able to support those from pre-processor so they cannot be taken from `expat_config.h` (and are probably not in `expat_config.h` for that reason).

**Comment by hartwork** [comment]
>  Any ideas what to do about that problem?

I'll answer my own question now: I think there is no fix. If anyone has ideas later: Happy to re-open the ticket.
