### ISSUE TITLE
Compilation error with a particular configuration

### ISSUE THREAD

**Issue by klebertarcisio** [libexpat/libexpat#352]
This bug report presents some error messages in an attempt to compile the Expat system with a particular configuration.

**Steps to reproduce:**
Branch: master 
git  clone https://github.com/libexpat/libexpat.git
cd  libexpat/expat  
sudo  ./buildconf.sh
sudo  ./configure CPPFLAGS='-UPTRCALL -UFASTCALL -UXML_ENABLE_VISIBILITY -UXML_MIN_SIZE -UPTRFASTCALL -UXML_UNICODE -UXML_UNICODE_WCHAR_T -UXML_ATTR_INFO -U_WIN32 -UXML_CONTEXT_BYTES -UXML_NS -UXML_LARGE_SIZE -UXML_DTD -UMIN_BYTES_PER_CHAR -UHAVE_EXPAT_CONFIG_H -UO_BINARY -UHAVE_UNISTD_H -U_DEBUG -U_MSC_VER  -DXML_TOK_IMPL_C -DXML_DTD -DW3C14N -DUNUSED_P'
sudo  make

**Operational System**
Distributor ID:Ubuntu
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic

**GCC**
gcc (Ubuntu 7.4.0-1ubuntu1 18.04.1) 7.4.0

Also, I would like to know what are the main configurations you are testing when developing Expat and if you use any tools to automate this process of testing various configurations.

**A report with details of the bug analysis is attached. Please, see the attachment.**
[Bug Report Expat.pdf](https://github.com/libexpat/libexpat/files/3660485/Bug.Report.Expat.pdf)

**Comment by RMJ10** [comment]
To summarize the actual bug report:

```
xmlparse.c: In function 'errorProcessor':
<command-line>:0:10: error: called object is not a function or function pointer
xmlparse.c:5270:3: note: in expansion of macro 'UNUSED_P'
  UNUSED_P(s);
  ^~~~~~~~
```
...and the same for the other three uses of `UNUSED_P` in xmlparse.c.  Apologies for any typos, I retyped that from a screenshot in a PDF.  The error arises because the definition of `UNUSED_P` in the setting of `CPP_FLAGS` in the `./configure` command is inconsistent with the way it is used in the code.

Bluntly, don't do that.

I have to admit I'm at a bit of a loss to explain why you thought providing an overriding definition of `UNUSED_P` or any of the other macros was a good idea.  This is just the most obvious problem with your configuration, I think there may be other more subtle problems that will bite you badly.  Really you shouldn't be directly defining `CPP_FLAGS` like that without a very good reason.  Please see the configuration help text (the result of running `./configure --help`) and use the appropriate flags.

**Comment by hartwork** [comment]
Hi Kleber,

> sudo ./configure CPPFLAGS='[..] -DUNUSED_P'

we don't currently support that configuration. 
To me the question here is if some other outer build system defines `UNUSED_P` for you or not. If yes, we can take steps to avoid that collision. If not and this is more like a try to make the build fail, I would consider this case as okay not to support. What do you think?

> Also, I would like to know what are the main configurations you are testing when developing Expat and if you use any tools to automate this process of testing various configurations.

We have integration for two CIs here — [.travis.yml](https://github.com/libexpat/libexpat/blob/master/.travis.yml) for Travis CI and [appveyor.yml](https://github.com/libexpat/libexpat/blob/master/appveyor.yml) for AppVeyor — that are worth a closer look. Ticket #324 also comes to mind. Does that answer the question?

**Comment by klebertarcisio** [comment]
Hello Sebastian and Rhodri, thanks for the replies.

I understand that this is not a system bug, but a currently invalid configuration.
Sebastian, thanks for introducing me to ticket 324, this is really something I was looking for. Once again, thank you very much for the answers.
