### ISSUE TITLE
Verify PGP signature / where to find GnuPG public key

### ISSUE THREAD

**Issue by meta-gitub** [libexpat/libexpat#397]
Sorry, to bother you with such a simple question, but where can I find the public PGP key which I need to verify the signature used in for example expat-2.2.9.tar.gz.asc.

In my test:
```console
# gpg --verify expat-2.2.9.tar.gz.asc  
gpg: assuming signed data in 'expat-2.2.9.tar.gz'
gpg: Signature made Thu Sep 26 00:04:30 2019 CEST
gpg:                using RSA key CB8DE70A90CFBF6C3BF5CC5696262ACFFBD3AEC6
gpg: Can't check signature: No public key
```

Thanks,

Thomas

**Comment by hartwork** [comment]
Does this work for you?:
https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3176ef7db2367f1fca4f306b1f9b0e909af37285

**Comment by hartwork** [comment]
If you need anything more, please let me know. Closing.

**Comment by meta-gitub** [comment]
Thanks, the link did help and also thanks for changing the title of this issue.

**Comment by ernstki** [comment]
> Does this work for you?: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3176ef7db2367f1fca4f306b1f9b0e909af37285

I've never been quite sure why some software projects publish the signing key alongside the releases, some projects tend to hide it away somewhere on the web site (such as under a "Contact Us" section), and some projects expect you to find the key on your own.

Zero judgments on any of those counts; everyone's efforts to keep these free software projects alive is appreciated. But what am I missing here? Oftentimes, I find a question like this in a mailing list archive, or an issue tracker, so it must be a common problem, or a common misconception.

Is the normal community expectation that someone will just use a keyserver to find the signing key, after receiving the message from `gpg --verify`?

**Comment by hartwork** [comment]
@ernstki I should only answer to part of that because other people can explain GPG better and this is not the best place but what I can say and think I understood is that people hosting pubkeys on their websites solves the man-in-the-middle problem (if you trust TLS) and if you trust it's their website.

**Comment by ernstki** [comment]
I can do up a proposal as a PR, and if you feel it improves the landing page without causing more confusion (that would result in more maintainer burden due to GitHub issues), great!

If not, no hard feelings. :)

**Comment by hartwork** [comment]
Hi @ernstki,

> **Edit**: I'm also prepared to accept that I'm in the very small minority of weirdos who always verify checksums and signatures on things. But I do feel that both of those things are important, and if the signatures and hashes or whatever are _made available_, it's good to nudge users in the right direction of what to do with them.

I'm with you on that, I remember being the only guy to check SSH fingerprints on first login to host X in company Y, so it's not so weird to me :smile: 

> I can do up a proposal as a PR, and if you feel it improves the landing page without causing more confusion (that would result in more maintainer burden due to GitHub issues), great!
> 
> If not, no hard feelings. :)

The part of me that feels some resistance here is that it would basically be doing work before requirements are clear which (from work experience and in work context) I would not recommend to anyone and feels like the wrong order. So let's clarify requirements and the problem to solve first so that pull request review will start with the big questions already answered, and have more of a chance to not be a waste of your and my time.

I guess for someone who wants to verify release artifacts the key questions (pun not intended :smiley:) would be (1) where to obtain the key used to sign from in a secure manner and potentially (2) how to verify a release in practice (e.g. through an example shell session or a list of commands).

For (1) starting today I am now self-hosting a current minimal armored pubkey export (produced with `gpg --armor --export --export-options export-minimal '3176 EF7D B236 7F1F CA4F  306B 1F9B 0E90 9AF3 7285'` at https://blog.hartwork.org/3176_EF7D_B236_7F1F_CA4F__306B_1F9B_0E90_9AF3_7285.asc which is (my blog and) a domain that I am controlling. If we want to add alternatives for backup, I'm aware of three options (that I have been feeding with updates myself in the past) as listed at https://github.com/libexpat/libexpat/issues/537#issuecomment-1003796884 .

A detail of potential interest is that the signing key is a actually a subkey…

```console
# gpg --list-packets < htdocs/3176_EF7D_B236_7F1F_CA4F__306B_1F9B_0E90_9AF3_7285.asc | grep -F keyid:
        keyid: 1F9B0E909AF37285
        keyid: BF9802AEE9F129C3
        keyid: 96262ACFFBD3AEC6  <-- this guy, but in too short of a format
```

… and that GitHub says it's expired as far as they are concerned [in a popup here](https://github.com/libexpat/libexpat/releases/tag/R_2_6_4)…

![expired](https://github.com/user-attachments/assets/7d76c88e-c04c-495f-8486-1f4221913198)

… and never alerted me about that. On a side note, blue is an interesting choice of color for something expired — great :smile: I will try to re-upload the pubkey to my GitHub profile to address that in a second.

How do you feel about answered and open questions about a pull request with that said?

**Comment by ernstki** [comment]
@hartwork I like the cut of your jib, sir.

I recently learned that [https://github.com/user.gpg retrieves a user's GPG key](https://stackoverflow.com/a/63618227), [_if_](https://github.com/ernstki.gpg) one has been added to the user's account.

That fact that it doesn't appear to be _documented_ anywhere (that I've found yet) is some cause for concern, though.

**Comment by hartwork** [comment]
@ernstki glad to hear :pray: So https://github.com/hartwork.gpg would be one more option for a pubkey source.

**Comment by gh-andre** [comment]
I found myself struggling with the same problem - where to find the public key. 

I will also add that using PGP makes sense when the key can be verified and otherwise a plain hash, like SHA-256, would work just as well. That is, when I import the public key and verify the file, I see the output below. Given that I downloaded the public key from the same repository (above), there's no more security in this signature than if I just copied a SHA-256 from the release notes.

> gpg --verify expat-2.7.1.tar.gz.asc expat-2.7.1.tar.gz
gpg: Signature made Thu 27 Mar 2025 03:48:10 PM EDT
gpg:                using RSA key CB8DE70A90CFBF6C3BF5CC5696262ACFFBD3AEC6
gpg: Good signature from "Sebastian Pipping <sping@gentoo.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 3176 EF7D B236 7F1F CA4F  306B 1F9B 0E90 9AF3 7285
     Subkey fingerprint: CB8D E70A 90CF BF6C 3BF5  CC56 9626 2ACF FBD3 AEC6

With regards to "weirdos" who verify packages, I have a script that downloads and builds libraries like `expat` and each time it downloads a package, it verifies the signature. So, "non-weirdos" using such scripts can rely on those signatures as well :)

**Comment by ernstki** [comment]
> I will also add that using PGP makes sense when the key can be verified and otherwise a plain hash, like SHA-256, would work just as well.

@gh-andre OK, agreed. Sometimes I get so caught up in _dutifully_ verifying GPG signatures, that I forget they're no better than a checksum over TLS if the signer is not "ultimately trusted" through a chain of other signatures.
