### ISSUE TITLE
Replace invalid characters

### ISSUE THREAD

**Issue by AdeleHoltmann** [libexpat/libexpat#430]
The company I work with wants to replace its XML parser and when I found expat I was very impressed.
Although I really like the code I would have to make a lot of changes because the customers do not want the parse process to end when invalid characters are found: They want to be informed about the invalid characters, the invalid characters be replaced (e.g. by '?') and the parse process to continue.
I have implemented this in the attached code which is based on release 2.2.10. (Invalid characters are only replaced in function doContent() in xmlparse.c) 
Would it be possible to integrate this functionality into expat? I could also implement tests.
[expat.zip](https://github.com/libexpat/libexpat/files/5659412/expat.zip)

**Comment by hartwork** [comment]
Hi Adele, 

thanks for taking this matter upstream. Before we go into details of code I would like to better understand the high level requirements. Before asking questions in that regard, let me present what I believe to be the relevant part of the XML 1.0r4 spec as implemented by Expat version 2.2.10 and earlier. There are two statements that I would like to highlight and quote:

> Violations of well-formedness constraints are fatal errors.

That's from https://www.w3.org/TR/2006/REC-xml-20060816/#dt-wfc . And also:

> It is a fatal error if an XML entity is determined (via default, encoding declaration, or higher-level protocol) to be in a certain encoding but contains byte sequences that are not legal in that encoding.

That's from https://www.w3.org/TR/2006/REC-xml-20060816/#charencoding .

So let's figure out together if and how those statements apply to our very case here.

With that base, I am interested in particular:
- What is an invalid character in your definition? I want to be 100% sure that we talk and think about the exact same thing.
- What is your (and/or that company's) motivation to tolerate and correct invalid characters?
- Is your input officially "labelled" as XML or are we actually dealing with things like [Apple p-list files](https://en.wikipedia.org/wiki/Property_list) or HTML here or something known to be XML-like but not actually well-formed XML?
- You said you're considering to switch to Expat. What are your requirements for a parser to switch to it?
- In particular, there are other libraries implementing a subset of XML and some that care less about being strict about interpreting the XML spec. Do you even need more than a subset of XML to be supported for your case?
- If your case violates the XML spec (as I'm suspecting at the moment), why is that a place you want to go and be?
- Why do you want to do that correction *inside* of Expat rather than *outside* of Expat in a self-made string pre-processor before passing data to Expat?

I'm looking forward to your reply.

Best, Sebastian

**Comment by AdeleHoltmann** [comment]
- What is an invalid character in your definition? I want to be 100% sure that we talk and think about the exact same thing.
_Let's say that the xml encoding is ISO-8859-1. The customers want to be informed about the byte 0x1B in the file._
- What is your (and/or that company's) motivation to tolerate and correct invalid characters?
_The customers receive xml files from another company that uses the xml format to export data from a database. Sometimes - for some strange reasons that I do not know, maybe because of a data migration in their database - some characters in their database's data change to invalid ones. The other company's "xml export" does not care and the customers receive these files and need to work with them: They need to use the data that they got from the other company but they also want to inform the other company that they have to correct their data._
- Is your input officially "labelled" as XML...
_Yes (sorry but this is true!)_
- You said you're considering to switch to Expat. What are your requirements for a parser to switch to it?
_We want to use a small library with no dependencies. - I think you know that Expat is a really great xml parser library, don't you?_
- In particular, there are other libraries implementing a subset of XML and some that care less about being strict about interpreting the XML spec. Do you even need more than a subset of XML to be supported for your case?
_Which other library do you recommend?_
- If your case violates the XML spec (as I'm suspecting at the moment), why is that a place you want to go and be?
_see above_
- Why do you want to do that correction inside of Expat rather than outside of Expat in a self-made string pre-processor before passing data to Expat?
_My self-made string processor would duplicate what expat does when reading the xml._

I appreciate your swift response and I perfectly understand your concerns! But still I would really like to use Expat - if you think that the only way to do this is use Expat as base and change the code for my needs: how can I update Expat to newer version when I have done so many changes?

**Comment by hartwork** [comment]
Thanks for your reply!

>  My self-made string processor would duplicate what expat does when reading the xml.

Could you elaborate why replacing bytes with value 27 (escape) by value 63 (question mark) will not be enough or too much?

**Comment by AdeleHoltmann** [comment]
I need this information for all supported encodings, therefore using your BYTE_TYPE would be fine (with your BT_NONXML and BT_LEAD2, BT_LEAD3, BT_LEAD4 combined with IS_INVALID_CHAR; every other BYTE_TYPE is ok).

**Comment by hartwork** [comment]
Hi Adele,

you said further up that the encoding can be assumed to be ISO-8859-1. So it sounds like that is no longer true.

I'm happy to further team up with you on addressing your situation *outside* of Expat for fun with voice calls in English or German if you like; if that's interesting to you, please find me at firstname@lastname.org with my name filled in so we can schedule a day and a time. Given how far you got with understanding and patching Expat internals, I have no doubt that you'll be able to tackle that challenge while still not producing extra costs for maintenance over time for yourself. `XML_SetXmlDeclHandler` may be of use to learn about on-the-fly change of encodings during parsing if you're aiming to be bullet-proof.

Because what you're trying to achieve is in violation with core parts of the XML spec it is not in the interest of Expat. Some company messed up their XML export: they are not the first and they will not be the last; that is not a problem of Expat. Thanks for your understanding.

Best, Sebastian
