### ISSUE TITLE
[2.3.0] Why CMakeLists prevents to use Visual Studio 2013 & 2015?

### ISSUE THREAD

**Issue by SpaceIm** [libexpat/libexpat#454]
@hartwork expat 2.3.0 seems to be perfectly valid for Visual Studio 2015 maybe even 2013, I can understand you don't want to test Visual Studio < 2017, but is there any reason to force an error in CMakeLists?

**Comment by hartwork** [comment]
Hi @SpaceIm , this comes to mind:

- (The original argument to add the check at #434 was that — as with `./configure` on Linux and Unix — the configuration stage should detect any problems *before* the compilation stage. That's the original idea.)

- Support for Visual Studio 2013 and 2015 was dropped in #447 because
  - 2015 is more than 5 years ago
  - the AppVeyor CI was wasting resources on those (which also slowed things down)
  - support for something always means cost to _someone_

For a way forward (and maybe before bringung up an idea about that) I would like to ask why support for MSVC 2013 or 2015 is needed in 2021 or what for. Could you elaborate? Thanks!

Best, Sebastian

**Comment by SpaceIm** [comment]
Let me clarify.

I'm packaging libraries for the conan public repository, and Visual Studio 2015 is tested. I don't have metrics, but there are issues asking to fix Visual Studio 2015 builds for several libraries, so I can assume that Visual Studio 2015 is still there in the industry (at least it will be maintained until end of 2025).

Anyway, I don't ask that expat supports Visual Studio 2013 or 2015, I don't use either.

If expat raises an error, we have to raise an error also in conan, and it prevents expat and all its downstreams to build for Visual Studio 2015 (or we need to use 2.2.10 in the dependency graph if Visual Studio < 2017): potentially libraries like GDAL, libkml, libarchive, ITK, POCO or APR.

But my main concern: is it a good idea to raise an error in CMakeLists for compilers that seem to be able to compile and consume expat?
One would consider as bad practice to assume that some compiler can't build a project just because it's not tested with this specific compiler: https://youtu.be/_5weX5mx8hc?t=436

**Comment by hartwork** [comment]
Sure is the industry using MSVC 2015 and forwarding the cost of supporting that for them to the community and unpaid volunteers, plain awesome :disappointed: We can do either of two things:
- We split the current hard error on "<1910/15.0/2017" into a big fat "officially unsupported compiler" warning for some value X and a hard error for value Y. We then need to determine good values for X and Y.
- You patch the check away in Conan. To save you repeated forward porting, we could extract numbers into constants so that when the numbers change the patch on your side does not, at least not every time.

What do you think?

**Comment by hartwork** [comment]
PS: To be concrete, for values X and Y how about:
- error for <1800/12.0/2013
- warning for <1910/15.0/2017

**Comment by SpaceIm** [comment]
Why not: no errors, warnings if you really want (at least we can try to compile if it works, even it's not tested). Update README to display the list of tested compilers, without assumption that previous compilers versions can't compile expat.

**Comment by hartwork** [comment]
Okay cool. Let me make a pull request for review.
With regard to the readme, I think the current wording "supported compilers" is not wrong so I'd keep the readme as is.
PS: I agree that rejecting compilers that *can compile* the code is not ideal.

**Comment by hartwork** [comment]
I made pull request #455 just now.
