### ISSUE TITLE
BUILD_SHARED_LIBS is not supported (was: Rename EXPAT_SHARED_LIBS to BUILD_SHARED_LIBS)

### ISSUE THREAD

**Issue by concatime** [libexpat/libexpat#471]
Hi.
Can you replace your own variable EXPAT_SHARED_LIBS by CMake’s documented BUILD_SHARED_LIBS?
It would ease a little bit maintainers’ life.
Thank you.

**Comment by hartwork** [comment]
Hi Issam,

let's find out if the off-default name is a bug or a feature. I'm still learning new things about CMake "every day" so if there is something to learn here — great.

Git history shows that `EXPAT_SHARED_LIBS` started out as a rename (in fce015875e6153d417c60818946073f6c6aae692) from older `BUILD_shared` to fit the `EXPAT_` namespace schema.  `BUILD_shared` was part of the CMake build system since its day one (b6db32746fc4df96c52ad3016d86a5f2a8585f56).  So I don't see obvious justification _for_ the non-default flag in Git history.  Two other things come to mind:

The default value of CMake's `BUILD_SHARED_LIBS` seems to be `OFF` (which I'm not sure is a good idea) so you only get shared libraries if you set it to `ON` manually.  If we move to `BUILD_SHARED_LIBS` we _may_ need a way to override the default (without dictating that value to neighbor projects in a multi-project CMake build at the same time).

The other aspect is that having a dedicated `EXPAT_SHARED_LIBS` may enable to effectively control `BUILD_SHARED_LIBS` for just libexpat in a multi-project CMake build.

Last but not least, do you have a link to where you maintain libexpat with -DEXPAT_SHARED_LIBS=OFF? Is this about about getting rid of `-DEXPAT_SHARED_LIBS=OFF` to reduce noise and go back to the default of static libraries or about something else?

Best


Sebastian

**Comment by 1480c1** [comment]
> The default value of CMake's `BUILD_SHARED_LIBS` seems to be `OFF` (which I'm not sure is a good idea) so you only get shared libraries if you set it to `ON` manually. If we move to `BUILD_SHARED_LIBS` we _may_ need a way to override the default (without dictating that value to neighbor projects in a multi-project CMake build at the same time).

as a note with no particluar opinion, you can do a simple
```cmake
option(BUILD_SHARED_LIBS "Build shared libraries (DLLs)." ON)
```
to make it default to `ON` as Google does with a lot of their CMake projects for the same reason and also to make it appear in a CMake gui as by default the variable is marked as advanced and hidden

**Comment by concatime** [comment]
I’m building my own mostly static linux distro. I have an automatic config which sets `BUILD_SHARED_LIBS` to `OFF` (just like `default_library=static` for Meson). Then, when looking at some binaries, I found out they were dynamically linked with libexpat. So I had to dig into expat’s CMakeLists.txt to find which variable controls the library type.
Also, having libexpat built statically by default is a non-issue. [LibreSSL does the same thing](https://github.com/libressl-portable/portable#cmake---additional-options). No need to touch `BUILD_SHARED_LIBS`.

**Comment by hartwork** [comment]
@1480c1 without further resarch, I'm unsure about scope in CMake. If we set default `ON` and someone includes libexpat by means of say `add_subdirectory`, will we affect the parent project's default?

@concatime I think LibreSSL not touching (but merely documenting) the off-by default nature doesn't prove much.  Given your static linux distro context, you probably have a general bias towards static libraries while I have an admitted general bias towards shared libraries, mostly for security reasons — does that sounds fair?

**Comment by 1480c1** [comment]
> @1480c1 without further resarch, I'm unsure about scope in CMake. If we set default `ON` and someone includes libexpat by means of say `add_subdirectory`, will we affect the parent project's default?

When a `project()` is called, it sets up a whole new scope and there is no way to leak it upwards unless written externally to a file or through some other `FILE` even when trying to use `set(var val PARENT_SCOPE)`

**Comment by hartwork** [comment]
@1480c1 that makes sense.

**Comment by concatime** [comment]
@hartwork I have a general bias towards “Convention over configuration”, that is letting CMake’s default choice.

**Comment by hartwork** [comment]
So it seems like we could stick with default `ON` with name `BUILD_SHARED_LIBS` without affecting neighbor projects, cool!

What about the separation aspect (the second last point [in my first reply](https://github.com/libexpat/libexpat/issues/471#issuecomment-830166716))? Let's say we have a project add adds libexpat and libressl using `add_subdirectory`, each. If both subprojects are controlled through `BUILD_SHARED_LIBS`, is there some way to to get shared libs from expat and static libs from libressl then? Is that needed? Are we sure it's *not* needed?

**Comment by 1480c1** [comment]
> Let's say we have a project add adds libexpat and libressl using `add_subdirectory`, each. If both subprojects are controlled through `BUILD_SHARED_LIBS`, is there some way to to get shared libs from expat and static libs from libressl then?

I think this would be as simple as
```cmake
project(over)
...
set(OVER_OLD_SHARED_LIBS ${BUILD_SHARED_LIBS})
set(BUILD_SHARED_LIBS ON)
add_subdirectory(libexpat/expat)
set(BUILD_SHARED_LIBS OFF)
add_subdirectory(libressl)
set(BUILD_SHARED_LIBS ${OVER_OLD_SHARED_LIBS})
```
>  Is that needed? Are we sure it's _not_ needed?

this can be useful for licensing reasons

**Comment by hartwork** [comment]
@1480c1 I was thinking more of the end user, i.e. without modifying files just by passing things to CMake on the command line. I should have been more clear about that. For inside `CMakeLists.txt`, your example seems to solve the case completely.

**Comment by 1480c1** [comment]
> @1480c1 I was thinking more of the end user, i.e. without modifying files just by passing things to CMake on the command line. I should have been more clear about that. For inside `CMakeLists.txt`, your example seems to solve the case completely.

From what I know, unless you have something like what you already have, it is virtually impossible

**Comment by 1480c1** [comment]
Usually the general idea is to rely on system libs first and fallback if necessary or error out using a FindModule.cmake thing as the idea of externalprojects and using add_subdirectory with another project was not part of the _grand design_ of cmake originally afaik so a lot of those kinds of things are more in a limbo with no clear upstream answer on how to do that from what I remember reading a long time ago

**Comment by concatime** [comment]
@1480c1 you’re right. This is one major difference beetween CMake and Meson.
