### ISSUE TITLE
Should expat.h #include expat_config.h?

### ISSUE THREAD

**Issue by swt2c** [libexpat/libexpat#505]
The reason I ask is that the new `XML_SetBillionLaughsAttackProtection*` methods are guarded under `#ifdef XML_DTD` but where is XML_DTD supposed to get defined?  Or are end user applications supposed to `#include <expat_config.h>` before including expat.h?

**Comment by hartwork** [comment]
Hi @swt2c good point, let me think about that more.

**Comment by hartwork** [comment]
@bachp not yet, thanks for the reminder

**Comment by hartwork** [comment]
@swt2c @bachp I thought about what would happen if we make `expat.h` include `expat_config.h`:

- It would pull all the other macros from `expat_config.h` into user code, not just `XML_DTD`. That could break source compatibility with projects that uses macros with the same name, e.g. the `PACKAGE_*` ones are more or less asking for a collision.
- It would make user code work with >=2.4.2 but not 2.4.0 or 2.4.1.

Having user code to include `expat_config.h` themselves does not seem to have either of these problems: It should work with 2.4.0 and 2.4.1 already today and allows addressing any potential macro conflicts rather than just running into them blindly.

What do you think?

**Comment by swt2c** [comment]
Seems okay to me - I just wanted to clarify the recommended approach either way.

**Comment by bachp** [comment]
@hartwork Fine for me too

**Comment by hartwork** [comment]
Thanks for the feedback :+1:, I'll close this topic as "answered, status quo good enough"…

**Comment by hartwork** [comment]
For the record, user code can also check for `XML_DTD` using the pre-processor as pointed out at https://github.com/pocoproject/poco/issues/3335#issuecomment-896839509.
