### ISSUE TITLE
Possible CVE

### ISSUE THREAD

**Issue by sevaksargsyan** [libexpat/libexpat#506]
Possible CVE-2009-3560 in file: https://github.com/libexpat/libexpat/blob/master/expat/lib/xmlparse.c
Look: https://github.com/smartpm/smart/commit/15914d21608f7e05ad936b44296c752b1e791f08

**Comment by hartwork** [comment]
@sevaksargsyan a quick look at the [change log](https://github.com/libexpat/libexpat/blob/ee695c78954edded24e5674722869daa69fd230a/expat/Changes#L770-L771) shows that these changes are supposed to be [included since Expat 2.1.0 in 2012](https://github.com/libexpat/libexpat/blob/ee695c78954edded24e5674722869daa69fd230a/expat/Changes#L770-L771).  Looking into Git history for confirmation I find these two related commits:
- a247ccd476970b9a0036379c584cb592cf08d79b
- 82d49517440c423bc0fb8e1672a8fee3c5e78716

Is there anything left here to investigate?

**Comment by sevaksargsyan** [comment]
File https://github.com/libexpat/libexpat/blob/master/expat/lib/xmlparse.c, line 4433 should be removed, according to fixing patch (https://github.com/smartpm/smart/commit/15914d21608f7e05ad936b44296c752b1e791f08)

**Comment by hartwork** [comment]
That line was re-added in 98a856ee200f1eada80c7808a325217d65e4b829, referring the same [SourceForge issue 2894085](https://sourceforge.net/p/expat/bugs/483/). So without deeper analysis, it looks like Smart did incomplete cherry-picking. Do you have any exploits or other evidence that the fix to either vulnerability in Expat is incomplete?

**Comment by sevaksargsyan** [comment]
No, sorry for false alarm.

**Comment by hartwork** [comment]
@sevaksargsyan okay, thanks for the update, I will close the ticket then.
