### ISSUE TITLE
Windows Expat 2.4.x does not build with Apache

### ISSUE THREAD

**Issue by SteffenAL** [libexpat/libexpat#508]
I cannot get expat 2.4.0 and 2.4.1  to  build on Windows in apr-util.

Using the /lib files 

With 2.4.0 I get include sys/random.h not found
Wirh 2.4.1 I get include expat_config.h not found

2.30 is all fine.

**Comment by hartwork** [comment]
@SteffenAL I'm happy to help but this is not an actionable complete bug report yet. I also have a feeling this will eventually not be a bug in Expat, e.g. if `expat_config.h` is not found then you're probably not using either of the two official build systems — GNU Autotools and CMake — and then it's likely not "Expat's fault". Mabe a quick video meeting would be the best use of your and my time. I'm on UTC+2, German and English work well for me if you're interested.

**Comment by SteffenAL** [comment]
I think sys/random is only on *nix.

For years Apache-Util is using the following dsp file and till 2.30 not a single issue.

[xml.zip](https://github.com/libexpat/libexpat/files/7032381/xml.zip)

**Comment by hartwork** [comment]
`.dsp` is Visual Studio 6 from the stone age. That's not a supported build system in 2021 with regard to Expat. Supported is "rolling ${today} minus 5 years" so that would be Visual Studio >=15.0/2017 as of today.

**Comment by SteffenAL** [comment]
Using Visual Studio C++ 2019 and the .dsp is converted nice to a vcproj file: 

[xml.zip](https://github.com/libexpat/libexpat/files/7032471/xml.zip)

**Comment by hartwork** [comment]
As I said, above the two supported build systems are GNU Autotools and CMake. CMake can produce Visual Studio 2019 solution files and those are supported because CMake and that compiler is. What you are doing is "off the road". How would you like to continue?

**Comment by SteffenAL** [comment]
What I do is official supported by Microsoft. 

A change in 2.4.x is causing this.

I continue with 2.3.0 for building at https://www.apachelounge.com  till someone comes with a solution.

Again, it worked for many years and now suddenly with 2.4 get errors.

**Comment by hartwork** [comment]
> What I do is official supported by Microsoft.

I don't see how that's relevant. Expat is not a museum.

> A change in 2.4.x is causing this.

Which one?

> I continue with 2.3.0 for building at https://www.apachelounge.com till someone comes with a solution.

That version is known vulnerable, so I don't advise running Expat before 2.4.0 in 2021. The change log has details about that.


> Again, it worked for many years and now suddenly with 2.4 get errors.

Likely because off your off-the-road build system. Without a proper bug report or a voice call I cannot do much for your case, I suppose.

**Comment by hartwork** [comment]
PS: Pull request #467 may have clues for how to fix things on your end.

**Comment by hartwork** [comment]
PPS: Expat >=2.4.0 requires a file `expat_config.h`. If neither CMake nor Autotools generate that file for you, you have to create such a file manually. Templates `expat_config.h.in` and `expat_config.h.cmake` may be of interest on that context.

**Comment by SteffenAL** [comment]
Thanks for the tip.
I first did a separate cmake  build expat, that is generating a expat_config.h which I copied to the Apache build-system.

**Comment by SteffenAL** [comment]
Forget to tell : get a warning

 c:\vc15\win64\httpd-2.4\srclib\apr-util\xml\expat\lib\xmlparse.c(7965): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

**Comment by hartwork** [comment]
> Forget to tell : get a warning
> 
> c:\vc15\win64\httpd-2.4\srclib\apr-util\xml\expat\lib\xmlparse.c(7965): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

That's another great example of why going off-the-road means extra work for you in practice: we have CMake configured to pass `_CRT_SECURE_NO_WARNINGS` at… https://github.com/libexpat/libexpat/blob/9f742632bae28dea97d6c4b77038608e932d05eb/expat/CMakeLists.txt#L326-L328 …and you only get that warning because you're not building with CMake. So you'll need to add it yourself. It's not a bug.

I'll close this ticket as "answered, not a bug".

**Comment by SteffenAL** [comment]
I think suppressing this kind of security warnings is not the way to go.  

Ok you can close.

**Comment by hartwork** [comment]
> I think suppressing this kind of security warnings is not the way to go.

@SteffenAL I'm the first to help fix security issues, no matter how small, rather than argue that something is hard to exploit or of limited damage: security matters.
However the current use of `getenv` in Expat is safe to my knowledge, and we compile with fatal warnings in the CI (so false positives need to be addressed to not fail the build) and `_CRT_SECURE_NO_WARNINGS` is mostly noise of questionable value, well-intended or not. So personally I'm good with `_CRT_SECURE_NO_WARNINGS` active, even with my security hat on. If you have in-depth evidence why I should reconsider that approach, please share that evidence with me via e-mail. Thank you.
