### ISSUE TITLE
How to compile in window. Although there are binary files in the package, I seem to need x64.

### ISSUE THREAD

**Issue by NatsuShio** [libexpat/libexpat#530]
How to compile in window. Although there are binary files in the package, I seem to need x64.

I need to use this library to compile `lxp.dll` of `luaexpat`.
The files I compiled with msys2 cannot be used. Checking the dll export table can clearly see that there is a problem.

Use the .dll file compiled by msys2.
![image](https://user-images.githubusercontent.com/46892084/147652699-c2204fa1-4269-4f0a-a096-57f21962567b.png)

Use the .so file compiled by msys2.
![image](https://user-images.githubusercontent.com/46892084/147652771-de1b0077-36b1-48dd-9752-8bafd2cd09b3.png)

or? Provide x64 binary related files?

**Comment by hartwork** [comment]
Hi @NatsuShio ,

if your compiler is Microsoft Visual Studio >=15.0/2017 then you could:

1. Run CMake to generate an MSVC solution file.
2. Run msbuild on that solution file.

That's what the AppVeyor Windows CI is doing for libexpat, e.g. see https://github.com/libexpat/libexpat/blob/60bbbe560cb50e6bfbf93ed765aaeb38335487c3/appveyor.yml#L111 

Does that answer your question?

**Comment by 1480c1** [comment]
If you are planning to use msys2, you should make sure you are using either the mingw64, ucrt64, or clang64 targetting dev environments instead of the cygwin-based msys one.  Based on seeing `C:/msys64/usr/local` instead of `C:/Program Files (x86)/expat` or `C:/msys64/mingw64/usr/local` or any of the others, leads me to believe you might be using the wrong subsystem.

Also, as far as I know, msys2 should never produce a .so file, in any of their subsystem. You might want to make sure that .so was properly compiled and check the subsytem you used, you should not mix them together as they all use slightly differing toolchains.

You might need to make sure to install the appropriate toolchain as well, so for mingw64, it would be

```bash
pacman -S --needed --noconfirm mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-toolchain
```

https://www.msys2.org/wiki/MSYS2-introduction/
https://www.msys2.org/docs/environments/

**Comment by NatsuShio** [comment]
> 嗨@NatsuShio，
> 
> 如果您的编译器是 Microsoft Visual Studio >=15.0/2017，那么您可以：
> 
> 1. 运行 CMake 以生成 MSVC 解决方案文件。
> 2. 在该解决方案文件上运行 msbuild。
> 
> 这就是 AppVeyor Windows CI 为 libexpat 准备的，例如，参见
> 
> https://github.com/libexpat/libexpat/blob/60bbbe560cb50e6bfbf93ed765aaeb38335487c3/appveyor.yml#L111
> 
> 这是否回答了你的问题？



> Hi @NatsuShio ,
> 
> if your compiler is Microsoft Visual Studio >=15.0/2017 then you could:
> 
> 1. Run CMake to generate an MSVC solution file.
> 2. Run msbuild on that solution file.
> 
> That's what the AppVeyor Windows CI is doing for libexpat, e.g. see
> 
> https://github.com/libexpat/libexpat/blob/60bbbe560cb50e6bfbf93ed765aaeb38335487c3/appveyor.yml#L111
> 
> Does that answer your question?

Thank you for your answer.

I tried it and the compilation succeeded. But it needs to be verified whether it can be used. If I still have questions, I still need your help. If there is no problem, I will close this issue

**Comment by NatsuShio** [comment]
> If you are planning to use msys2, you should make sure you are using either the mingw64, ucrt64, or clang64 targetting dev environments instead of the cygwin-based msys one. Based on seeing `C:/msys64/usr/local` instead of `C:/Program Files (x86)/expat` or `C:/msys64/mingw64/usr/local` or any of the others, leads me to believe you might be using the wrong subsystem.
> 
> Also, as far as I know, msys2 should never produce a .so file, in any of their subsystem. You might want to make sure that .so was properly compiled and check the subsytem you used, you should not mix them together as they all use slightly differing toolchains.
> 
> You might need to make sure to install the appropriate toolchain as well, so for mingw64, it would be
> 
> ```shell
> pacman -S --needed --noconfirm mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-toolchain
> ```
> 
> https://www.msys2.org/wiki/MSYS2-introduction/ https://www.msys2.org/docs/environments/
Thank you for your answer.

The `.so` file is obtained by using `luarocks install luaexpat` command after compiling and installing `luarock` in `msys2`.
The compiler I use is mingw。

**Comment by hartwork** [comment]
@NatsuShio since you mention MinGW, I should add:
- for CMake `-DCMAKE_TOOLCHAIN_FILE=cmake/mingw-toolchain.cmake` may be of interest. The related file is part of this repository.
- There also is a configure script (that you can generate by running `./buildconf.sh` in case of a Git clone) and it understands `--host=i686-w64-mingw32` for MinGW.

Both of these approaches can be seen in action at CI file https://github.com/libexpat/libexpat/blob/master/.github/workflows/autotools-cmake.yml#L51-L52 .

**Comment by NatsuShio** [comment]
> @NatsuShio since you mention MinGW, I should add:
> 
> * for CMake `-DCMAKE_TOOLCHAIN_FILE=cmake/mingw-toolchain.cmake` may be of interest. The related file is part of this repository.
> * There also is a configure script (that you can generate by running `./buildconf.sh` in case of a Git clone) and it understands `--host=i686-w64-mingw32` for MinGW.
> 
> Both of these approaches can be seen in action at CI file https://github.com/libexpat/libexpat/blob/master/.github/workflows/autotools-cmake.yml#L51-L52 .

Thank you so much.

I tried to use `lua` to load the compiled `dll` file, and it loaded successfully.I want to close this issuse.
I don't understand this paragraph. Which tools or environments are these related to? The file mentioned is the configuration file of those tools. I want to learn it briefly.

**Comment by hartwork** [comment]
> Which tools or environments are these related to?

- Files `./buildconf.sh` and `./configure` are GNU Autotools, and they work on Unix-oid systems and with MinGW on Windows
- The rest is CMake, and that works everywhere.
- Both are build systems, the two that libexpat supports and comes with.
