### ISSUE TITLE
[>=2.3.0] xmlwf: Memory leak on output file opening error

### ISSUE THREAD

**Issue by hwt0415** [libexpat/libexpat#544]
In file xmlwf.c line 1179, need to call `free(outName);` out of if condition, no matter it's continueOnError or not. Otherwise there is risk of memory leak.

**Comment by hartwork** [comment]
Hi @hwt0415 are you aware of the free at?:
https://github.com/libexpat/libexpat/blob/57c7da69b78e3698e112a6b5da19d5109b8232d1/expat/xmlwf/xmlwf.c#L1242 
Isn't that doing the job you're looking for?

**Comment by hwt0415** [comment]
Hi @hartwork ,
Yes I see it. But one point I'm still confused:
When outName is not freed at line 1179(not continueOnError), is it always true that code will enter line 1235 `if (outputDir)` and free(outName)?
At line 1165, I think even if outputDir is null, code will still malloc outName. Not sure if I understand it correct or not.

**Comment by hartwork** [comment]
Hi @hwt0415,


thanks for your persistance :+1: I had a closer second look myself now and I confirm that at `break;` in [`xmlwf.c line 1183`](https://github.com/libexpat/libexpat/blob/57c7da69b78e3698e112a6b5da19d5109b8232d1/expat/xmlwf/xmlwf.c#L1183) there is a leak; it's missing even more than just `free(outName)`.  Here is how to see the leak in action with a live summary from Clang LeakSanitizer:

```console
# cd "$(mktemp -d)"
# git clone --depth 1 https://github.com/libexpat/libexpat/
# cd libexpat/expat
# mkdir build
# cd build
# cmake -DCMAKE_C_COMPILER=clang -DCMAKE_C_FLAGS="-std=c99 -pipe -Wall -Wextra -pedantic -Wno-overlength-strings -Wno-long-long -g -fsanitize=address -fno-omit-frame-pointer -fno-common -g3 -pipe" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-std=c++98 -pipe -Wall -Wextra -pedantic -Wno-overlength-strings -Wno-long-long -g -fsanitize=address -fno-omit-frame-pointer -fno-common" -DCMAKE_LINKER=clang++ -DCMAKE_EXE_LINKER_FLAGS="-g -fsanitize=address" -DCMAKE_MODULE_LINKER_FLAGS="-g -fsanitize=address" -DCMAKE_SHARED_LINKER_FLAGS="-g -fsanitize=address"  -DEXPAT_WARNINGS_AS_ERRORS=ON -DEXPAT_ATTR_INFO=ON ..
# make
# mkdir -m 0 outdir
# ./xmlwf/xmlwf -d outdir -r <(echo '<hello/>')
outdir/63: Permission denied

=================================================================
==25458==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x49b10d in __interceptor_malloc [..]/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x4d01e7 in main [..]/libexpat/expat/xmlwf/xmlwf.c:1165:29
    #2 0x7f26fbcc91c9  (/lib64/libc.so.6+0x291c9)

Indirect leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x49b10d in __interceptor_malloc [..]/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x7f26fbfbccbc in parserCreate [..]/libexpat/expat/lib/xmlparse.c:1018:21
    #2 0x7f26fbfbc408 in XML_ParserCreate_MM [..]/libexpat/expat/lib/xmlparse.c:966:10
    #3 0x7f26fbfbc3cb in XML_ParserCreate [..]/libexpat/expat/lib/xmlparse.c:715:10
    #4 0x4cff7b in main [..]/libexpat/expat/xmlwf/xmlwf.c:1114:16
    #5 0x7f26fbcc91c9  (/lib64/libc.so.6+0x291c9)

Indirect leak of 984 byte(s) in 1 object(s) allocated from:
    #0 0x49b10d in __interceptor_malloc [..]/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x7f26fbfbc742 in parserCreate [..]/libexpat/expat/lib/xmlparse.c:986:26
    #2 0x7f26fbfbc408 in XML_ParserCreate_MM [..]/libexpat/expat/lib/xmlparse.c:966:10
    #3 0x7f26fbfbc3cb in XML_ParserCreate [..]/libexpat/expat/lib/xmlparse.c:715:10
    #4 0x4cff7b in main [..]/libexpat/expat/xmlwf/xmlwf.c:1114:16
    #5 0x7f26fbcc91c9  (/lib64/libc.so.6+0x291c9)

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x49b10d in __interceptor_malloc [..]/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x7f26fbfbc9a8 in parserCreate [..]/libexpat/expat/lib/xmlparse.c:1003:22
    #2 0x7f26fbfbc408 in XML_ParserCreate_MM [..]/libexpat/expat/lib/xmlparse.c:966:10
    #3 0x7f26fbfbc3cb in XML_ParserCreate [..]/libexpat/expat/lib/xmlparse.c:715:10
    #4 0x4cff7b in main [..]/libexpat/expat/xmlwf/xmlwf.c:1114:16
    #5 0x7f26fbcc91c9  (/lib64/libc.so.6+0x291c9)

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x49b10d in __interceptor_malloc [..]/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x7f26fbfbcb27 in parserCreate [..]/libexpat/expat/lib/xmlparse.c:1009:39
    #2 0x7f26fbfbc408 in XML_ParserCreate_MM [..]/libexpat/expat/lib/xmlparse.c:966:10
    #3 0x7f26fbfbc3cb in XML_ParserCreate [..]/libexpat/expat/lib/xmlparse.c:715:10
    #4 0x4cff7b in main [..]/libexpat/expat/xmlwf/xmlwf.c:1114:16
    #5 0x7f26fbcc91c9  (/lib64/libc.so.6+0x291c9)

Indirect leak of 360 byte(s) in 1 object(s) allocated from:
    #0 0x49b10d in __interceptor_malloc [..]/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x7f26fbfcd41b in dtdCreate [..]/libexpat/expat/lib/xmlparse.c:6539:19
    #2 0x7f26fbfbcf7c in parserCreate [..]/libexpat/expat/lib/xmlparse.c:1032:21
    #3 0x7f26fbfbc408 in XML_ParserCreate_MM [..]/libexpat/expat/lib/xmlparse.c:966:10
    #4 0x7f26fbfbc3cb in XML_ParserCreate [..]/libexpat/expat/lib/xmlparse.c:715:10
    #5 0x4cff7b in main [..]/libexpat/expat/xmlwf/xmlwf.c:1114:16
    #6 0x7f26fbcc91c9  (/lib64/libc.so.6+0x291c9)

SUMMARY: AddressSanitizer: 3402 byte(s) leaked in 6 allocation(s).
```

For the _non-error_ case, the complete clean-up code is this:
https://github.com/libexpat/libexpat/blob/57c7da69b78e3698e112a6b5da19d5109b8232d1/expat/xmlwf/xmlwf.c#L1235-L1243

So we need all of that _minus_ the bits that do not need undo because they haven been done:
- `metaEndDocument(parser)` is *not* needed because `metaStartDocument(parser);` has not been run yet
- `fclose(userData.fp)` is *not* needed because opening the file failed
- `tremove(outName)` is *not* needed because creating the file failed
- `free(outName)` is needed as you reported
- `XML_ParserFree(parser)` is needed as well, that's the second thing missing.

I have opened a pull request #545 to address this issue, please feel invited to review of that approach. With that patch applied, LeakSanitizer is now happy over here.

If you feel safe with sharing your real name with the community, I'd like to credit your contribution with your real name rather than your alias in the change log.  Would that work for you?

Best, Sebastian

CC @timbray

**Comment by hwt0415** [comment]
Hi @hartwork, 

Thanks for your quick response
I'm okay for putting my real name in the change log :)

Best,
Wentao

**Comment by hartwork** [comment]
> Thanks for your quick response I'm okay for putting my real name in the change log :)
> 
> Best, Wentao

@hwt0415 Cool! I'm guess that Wentao is your first name? What should I put for last name?

**Comment by hartwork** [comment]
@hwt0415 your last name is the last thing needed to merge #545. Do you have a minute?
