### ISSUE TITLE
Include Version Info in dll-FileInfo

### ISSUE THREAD

**Issue by dskeller** [libexpat/libexpat#555]
As of CVE-2022-23852 and CVE-2022-23990 it would be helpful to have the version included in the dlls.
Currently the version is always '0.0.0.0'

Version can be checked with '(Get-Item [dll-File]).VersionInfo.FileVersion' or '(Get-Command [dll-File]).Version'

This would help find vulnerable files.

**Comment by hartwork** [comment]
Hi @dskeller can you provide a pull request to make the CMake build system put the version in at build time?

**Comment by hartwork** [comment]
Note to self: this may work: https://stackoverflow.com/a/36731183/11626624

**Comment by sgarske** [comment]
Hi, maybe this should be created as a separate issue so I apologize if this is the wrong place, but I believe there may still be an issue where the `VER_FILEVERSION` macro is not being resolved before being set for the `ProductVersion` in the FileInfo.
![image](https://github.com/libexpat/libexpat/assets/7501210/5b6ad79e-71cf-44fb-ac3a-6a246dfd5771)

Using the command above will return the macro name rather than the expected version
>PS C:\Whatever> (Get-Item libexpat.dll).VersionInfo.FileVersion
VER_FILEVERSION

I believe it might need some extra step to "stringify" the value - https://stackoverflow.com/a/59571399

This has caused some external security tooling to report the version as "unknown" still.

**Comment by hartwork** [comment]
@sgarske thanks for bringing this up but it's indeed not the best place and I have no access to true Windows or PowerShell outside of the CI, all my boxes are Linux. Other sources indicate that file version and product version work the same way so this issue is a bit of a surprise. This will take a pull request to fix or a dedicated issue and then someone else to join in. A way to extract version info from a given DLL file using MinGW tools on a Linux shell would also help, I don't find anything like that with a bit of Googling easily.

**Comment by hartwork** [comment]
@sgarske quick update: I found gist https://gist.github.com/spookyahell/b317bdf0712aac5fd37dd79f70bfbe69 now and was able to reproduce (and hopefully fix) the problem on my Linux box. Could give pull request #785 a try? That would rock, thanks! :pray:
