### ISSUE TITLE
[>=2.4.5] After fixing CVE-2022-25236, some xml texts cannot be parsed properly?

### ISSUE THREAD

**Issue by linzhuorong** [libexpat/libexpat#604]
https://github.com/libexpat/libexpat/pull/561/

A test case in python's dependency package expat return a syntax error.
 ```
def test_issue3151(self):
    e = ET.XML('<prefix:localname xmlns:prefix="${stuff}"/>')
    self.assertEqual(e.tag, '{${stuff}}localname')
    t = ET.ElementTree(e)
    self.assertEqual(ET.tostring(e), b'<ns0:localname xmlns:ns0="${stuff}" />')
```
Variables like `"${stuff}"` in text `<prefix:localname xmlns:prefix="${stuff}"/>' ` are not parsed properly.

I found out that '{' and '}' are missing from the [commit](https://github.com/libexpat/libexpat/commit/2ba6c76fca21397959145e18c5ef376201209020), which returns XML_FALSE;

**Comment by hartwork** [comment]
Hi @linzhuorong , the behavior you describe is _intended_.

What is happening:
- `ET.XML` calls `EXPAT(ParserCreate_MM)(encoding, &ExpatMemoryHandler, "}")` which tells Expat to use `}` (right closing curly bracket) for a namespace separator.
- The XML contains `}` in a namespace prefix URI.
- (Expat is allowed to reject it since `}` is not an allowed character in a URI and XML 1.0 parsers are allowed to reject namespace URIs that are not well-formed URIs with respect to RFC 3986.)
- Expat claims its right and returns a parse error since 2.4.5, because of security implications.
- The related losing that happened soon after in 2.4.7 does not change anything about `}` characters, because of `}` not being allowed in RFC 3986.

Does that answer the question?

**Comment by linzhuorong** [comment]
I get it, thinks!
