### ISSUE TITLE
considering adding meson build system

### ISSUE THREAD

**Issue by vtorri** [libexpat/libexpat#623]
meson has some advantages :

 * simpler syntax than cmake
 * a bit faster than cmake
 * it just works, no hacks like one can find in cmake
 * cross-compilation is easier to set up
 * options are clearly available in a separate file, no need to find them in all the CMakeLists.txt or in cmake/

**Comment by eli-schwartz** [comment]
> Pavel Rojtberg's article ["Do not use Meson"](https://www.rojtberg.net/1481/do-not-use-meson/) to be spot on to this day, and

This article *literally* says "Meson is better than cmake, therefore as a result you should not use it".

It boggles my mind that people read that article without bursting out laughing?

- "Recently, projects started using Meson and being happy using meson. It is time to stop that."
- "People replying to this article rightfully note that Meson has advantages X, Y, and Z. But it's still bad to use Meson, because people should instead improve CMake's documentation and add cmake educational warnings".
- "Meson makes building software worse, because the literal act of creating another build system causes standards to proliferate, and that's bad".

> Meson rather unstable (e.g. see https://bugs.gentoo.org/831474 for the mass-breakage that meson 0.61 caused),

This was caused by gnome software that passed an invalid argument for a function that was documented to not accept one, and routine refactoring caused Meson to actually check that. While I would not say that Meson is bug-free (I doubt you will find software that is bug-free) I think that it's not too bad if something breaks when:
- it's a bug in the project build files
- the error message clearly tells you how to fix it in a backwards-compatible manner
- the fix is to remove something from your build files that was unnecessary and never did anything

> CMake to have all features we need today,

This is actually all you needed to say. No need for the FUD. :)

**Comment by eli-schwartz** [comment]
Anyway, this makes me sad, because Meson has https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/expat/ which seems to be solving a fair number of people's problems, and I would have liked at some point to polish it up ("# TODO: tools, examples, tests, docs") and offer it here.

Why do I care about having meson support upstream here? Because there's interest either way. Supporting Meson isn't just about canonically building it that way, it also allows integrating it into a Meson-using project (especially important on Windows, which lacks OS package managers). And having that support be integrated rather than third-party can be beneficial.

It's something I'd be willing to offer support for, even.

But if your policy here is that an article which literally reprimands and tells people off if they commit "crimes against the global C/C++ ecosystem by using Meson and fragmenting the community", is "spot on to this day", then I guess I'll take that off my TODO list.

**Comment by hartwork** [comment]
@eli-schwartz thanks for sharing your view. Please understand that I will now lock this discussion so that the Expat issue tracker doesn't turn into a build system flame war from any future replies coming in. I needed to answer to the initial request and I felt it deserved a proper reply. Now you had your chance to add your view, that's all we needed here (or more) in my eyes. If you consider locking this thread now unfair, please contact me off-GitHub through e-mail on that topic. Thank you :pray:
