### ISSUE TITLE
Add additional tags with semantic versioning ("X.Y.Z" or "vX.Y.Z")

### ISSUE THREAD

**Issue by jfcalvo** [libexpat/libexpat#661]
I believe it would be nice to have additional tags with semantic versioning so instead of having `R_2_4_9` we have `2.4.9` or `v2.4.9`.

I guess this can break some integrations with the library so maybe it's so easy as adding additional tags like `2.4.9` linked to the same commit hash that `R_2_4_9`.

Thanks for the library.

**Comment by hartwork** [comment]
Hi @jfcalvo the `R_x_y_z` format is from years ago and has been continued as such for consistency. I'm not strongly objecting to changes or additions in this area but my impression so far is that (1) this is a general idea rather than a concrete pressing scenario, that (2) I see little practical gains outside of beauty, and that (3) mass pushing git tags would cause a lot of failing CI runs, or 2.4.9 would be the starting point of things and then beauty can be argued and (4) dropping the old tags will break some downstreams (as you mentioned) and (5) there are other tags but `R_x_y_z` ones that are also not exactly clean and will hinder beauty across all tags or cause additional work. So there are considerations and work to be done here that only are worth the investment if there are practical gains in my book. What would be those practical gains today?

**Comment by jfcalvo** [comment]
> I see little practical gains outside of beauty.

I would say uniformity or homogeneity instead of beauty. 🙂

> What would be those practical gains today?

From my side: don't need to implement a special case for libexpat on the scripts that I use to automatically download dependencies and specify versions.

I was hoping adding new tags to the repo wouldn't be a problem. If that's not the case then I don't think it's something should be done.

Thank you very much Sebastian for taking the time to response to my suggestion.
