### ISSUE TITLE
Getting compile time error with VS2012 in expat 2.4.9

### ISSUE THREAD

**Issue by AshishDurgapal** [libexpat/libexpat#676]
As we know that expat 2.4.9 does not support the VS2012 officially but for our application we need expat 2.4.9 which is compataible with 2012 service.

I have created the Expat lib in vs 2015 and now I am trying to compile the service in vs2012 which uses the expat lib of version 2.4.9 but getting given errors.
   error LNK2001: unresolved external symbol ___acrt_iob_func              libexpatMT.lib(xmlparse.obj)               
   error LNK2001: unresolved external symbol ___stdio_common_vfprintf          libexpatMT.lib(xmlparse.obj)               
  error LNK2001: unresolved external symbol __fdclass             libexpatMT.lib(xmlparse.obj)               
  error LNK2001: unresolved external symbol __ultod3             libexpatMT.lib(xmlparse.obj)

**Comment by hartwork** [comment]
Hi @AshishDurgapal ,

this is a bit of a weird report since you seem clear that this is beyond the line of officially supported :thinking:  I'm not sure why you'd want to miss out on the bug- and security fixes from Expat 2.5.0 or use VS as ancient as that, but if that's a given on your end all I can think of offering is two things:

- Try to reproduce the error with MSVC 15.0/2017 — the oldest officially supported today —, get to the core of the issue, and then we can team up on fixing that version of the issue as something of relevance to the community.
- Run CMake to _generate_ an MSVC solution file `expat.sln` on the fly using [CMake's built-in generators](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#id14) — either `Visual Studio 12 2013` or `Visual Studio 14 2015` — similar to what Expat's AppVeyor CI does at
https://github.com/libexpat/libexpat/blob/441f98d02deafd9b090aea568282b28f66a50e36/appveyor.yml#L138
and hope for that to work out of the box like it did not too long ago, or continue the journey from there.

What do you think? How would you like to continue?

**Comment by AshishDurgapal** [comment]
Hi @hartwork ,

I have tried by using the cmake built-in generators using the given command.
  "cmake -G "Visual Studio 11 2012" -DEXPAT_MSVC_STATIC_CRT=ON -DEXPAT_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release .."

but we are not even able to configure the expat for VS2012 as it is not supported now.

Regarding your first point : I don't think you will face any issue with MSVC 15.0/2017 as the error I mentioned is specific to vs 2012.
but yes if you are trying to say you will build the lib with MSVC 15.0/2017 and then you will link that lib with application built on VS2012. This way you will able to reproduce the same,

**Comment by hartwork** [comment]
> Hi @hartwork ,
> 
> I have tried by using the cmake built-in generators using the given command. "cmake -G "Visual Studio 11 2012" -DEXPAT_MSVC_STATIC_CRT=ON -DEXPAT_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release .."
> 
> but we are not even able to configure the expat for VS2012 as it is not supported now.

@AshishDurgapal it you're running into the error produced by the CMake code at https://github.com/libexpat/libexpat/blob/441f98d02deafd9b090aea568282b28f66a50e36/expat/CMakeLists.txt#L184-L202 that would need to be patched out or adjusted in your local copy. For any more changes to the code pull request #426 may be of interest, in particular commit `Drop remaining support for Visual Studio 2008, 2010, 2012`.

> Regarding your first point : I don't think you will face any issue with MSVC 15.0/2017 as the error I mentioned is specific to vs 2012. but yes if you are trying to say you will build the lib with MSVC 15.0/2017 and then you will link that lib with application built on VS2012. This way you will able to reproduce the same,

I had an all-2017 scenario in mind. As soon as 2012 enters the picture, we're entering unsupported territory.

How would you like to continue?

**Comment by hartwork** [comment]
Closing as "not supported in 2022"…
