### ISSUE TITLE
Rename struct ELEMENT_TYPE to XML_ELEMENT_TYPE to avoid name collision

### ISSUE THREAD

**Issue by Krausal** [libexpat/libexpat#681]
In windows the name ELEMENT_TYPE is already used. Therefore there are problems when using libexpat in VisualStudio (winioctl.h). Changing the name of the struct ELEMENT_TYPE to XML_ELEMENT_TYPE in xmlparse.c would solve this problem.

**Comment by hartwork** [comment]
Hi @Krausal,

I found [ELEMENT_TYPE in MSDN](https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ne-winioctl-element_type).  My understanding is that there is a conflict with an internal non-header structure name only because you are including or embedding the source code of `xmlparse.c` inside another C/C++ file, otherwise the Windows CI would have broken long before. What is your motivation to do that?

**Comment by Krausal** [comment]
Hello @hartwork 
not only we want to have access to the source code in our software for debugging causes but also we are delivering our software on several platform. Therefore it is much easier for our toolchain to use it this way.

**Comment by hartwork** [comment]
@Krausal I don't see how that would require embedding or including `xmlparse.c` *into another C/C++ file* — compiling as a separate unit that is being linked against should work fine for what you describe regarding debugging and several platforms. What am missing?

**Comment by hartwork** [comment]
No reply for three months, issue considered in the way Expat is being used until clarified further, closing.
