### ISSUE TITLE
Is the CVE-2013-0340  modified in libexpat 2.3.0?

### ISSUE THREAD

**Issue by lixiaoshuai666** [libexpat/libexpat#768]
Is there any patch modified?

**Comment by hartwork** [comment]
@lixiaoshuai666 I don't understand the question. The fix to CVE-2013-0340 was introduced with #466 and first released with Expat 2.**4**.0. Please help me understand your question.

**Comment by hartwork** [comment]
@lixiaoshuai666 if the question was meant to be about the availability of a backport of pull request #466 to libexpat 2.3.0: I am not aware of any backports of this non-trivial fix to earlier versions of libexpat, e.g. Debian has backports of other fixes but not this one (see https://sources.debian.org/patches/expat/). My advice would be to upgrade to libexpat 2.5.0 with [multiple security fixes more](https://github.com/libexpat/libexpat/blob/master/expat/Changes) after 2.3.0 two and half years ago. Upgrading to 2.5.0 will also make timely upgrading to >=2.6.0 easy when that will be released later this year. I'll close this ticket as answered, happy to re-open if the question turns out as not answered.
