### ISSUE TITLE
Issue in max_slowdown value in basic_tests.c file 

### ISSUE THREAD

**Issue by atul20031** [libexpat/libexpat#825]
Hi, I am trying to build the expat 2.6 in maca634 platform and the unittests are failing with the following log:

bat122084maca64:tests batserve$ ./runtests
Expat version: expat_2.6.0
taken=7296 baseline=377 slowdown=19 max_slowdown=15
ERROR: Compared to the baseline runtime of the first test, this test has a slowd                              own of more than <max_slowdown>. Please keep increasing the value by 1 until it                               reliably passes the test on your hardware and open a bug sharing that number wit                              h us. Thanks in advance!
FAIL [chunksize=0 deferral=1]: test_big_tokens_take_linear_time (max_slowdown=15                               text="<e><aaaaaa/></e>" at basic_tests.c:5300)
99%: Checks: 4320, Failed: 1
bat122084maca64:tests batserve$ ./runtests_cxx
Expat version: expat_2.6.0
taken=8301 baseline=379 slowdown=21 max_slowdown=15
ERROR: Compared to the baseline runtime of the first test, this test has a slowd                              own of more than <max_slowdown>. Please keep increasing the value by 1 until it                               reliably passes the test on your hardware and open a bug sharing that number wit                              h us. Thanks in advance!
FAIL [chunksize=0 deferral=1]: test_big_tokens_take_linear_time (max_slowdown=15                               text="<e><aaaaaa/></e>" at ./basic_tests.c:5300)
99%: Checks: 4320, Failed: 1

**Comment by hartwork** [comment]
Hi @atul20031 sorry to hear, @Snild-Sony kindly already improved the situation in pull request #817. I am wondering two things now:
- is applying pull request #817 as a patch on top an option in your environment?
- how much trouble does/will it cause to you in practice?

Depending on your answers either the situation is good enough with a fix merged to `master` OR we should do a soon release 2.6.1, just because of this issue. Please help me better understand the situation, a new release takes 2+ me hours minimum. If it's needed, it's needed, but I'd like to be reasonably sure it is. Thanks!

**Comment by matshch** [comment]
https://github.com/NixOS/nixpkgs staging branch is broken for aarch64-darwin due to this issue. Looks like #817 helps to fix the issue, I can try to push just the patch to nixpkgs, but having a proper release would be nicer.

**Comment by hartwork** [comment]
@matshch thanks for elaborating. There are other Expat topics in flight at the moment that will need more clarity before making a decision about a release. The more we reach a state of plateau on the next few days (if that picture makes sense), the more likely a soon release.

**Comment by hartwork** [comment]
Closing as fixed on `master`…

With regard to release 2.6.1, there are ticket #832 and pull request #834 now.
