### ISSUE TITLE
[>=2.6.0] StartElementHandler not triggered in some cases?

### ISSUE THREAD

**Issue by jschueller** [libexpat/libexpat#840]
since version 2.6.0 this example does not trigger the startElement callback
we're adding the element "<Foo />" in two separate parse steps:

```c
#include <stdio.h>
#include <string.h>
#include <expat.h>

static void XMLCALL
startElement(void *userData, const XML_Char *name, const XML_Char **) {
  printf("--startElement name=%s\n", name);
}

int main(void) {
  XML_Parser parser = XML_ParserCreate(NULL);
  int done = 0;
  XML_SetElementHandler(parser, startElement, NULL);
  const char c0[] = "<?xml version=\"1.0\"?>";
  if (XML_Parse(parser, c0, strlen(c0), done) == XML_STATUS_ERROR)
    return 1;
  const char c1[] = "<Foo ";
  if (XML_Parse(parser, c1, strlen(c1), done) == XML_STATUS_ERROR)
    return 2;
  printf("closing Foo...\n");
  const char c2[] = "/>";
  if (XML_Parse(parser, c2, strlen(c2), done) == XML_STATUS_ERROR)
    return 3;
  XML_ParserFree(parser);
  return 0;
}
```

v2.5.0 output:
```
closing Foo...
--startElement name=Foo
```

v2.6.0 output:
```
closing Foo...
```

I believe this change of behavior is at the root of https://gitlab.kitware.com/vtk/vtk/-/issues/19258

bisecting points to 9cdf9b8d, cc @Snild-Sony

**Comment by hartwork** [comment]
Hi @jschueller,

the example code is missing (a) something like `XML_Parse(parser, "", 0, 1);` before `XML_ParserFree(parser);` or (b) disabling reparse deferral using >=2.6.0 API function [`XML_SetReparseDeferralEnabled`](https://libexpat.github.io/doc/api/latest/#XML_SetReparseDeferralEnabled); the latter would disable protection against quadratic runtime denial of service — the very security vunerability that Expat 2.6.0 started protecting against by default.

So this is expected behavior; it was introduced by pull request #789 to fix CVE-2023-52425.

Best, Sebastian

CC @Snild-Sony

**Comment by jschueller** [comment]
yes,  the actual vtk code relies on startElement being called before done=1 is passed to XML_Parse to trigger other parts of data to be parsed but I guess something else can be devised on the vtk side before disabling the protection
thanks for the quick reply

**Comment by hartwork** [comment]
@jschueller sounds great, thanks for the update, good luck! :+1:
