### ISSUE TITLE
Debian and Ubuntu packages failing with version 2.6.2

### ISSUE THREAD

**Issue by soluwalana** [libexpat/libexpat#857]
The most recent change apparently broke tests and is preventing the security fix from being upgraded to Debian's `testing` branch from `unstable`. 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064762

https://qa.debian.org/excuses.php?package=expat

Should these tests fail after the change?

**Comment by hartwork** [comment]
Hi @soluwalana, thanks for bringing this to my attention.

The issue there is likely from 2.6.0 (CVE-2023-52425, pull request #789) already rather than something later.
There are three projects know to me that have touch points with the fix:
- CPython (tests only)
- ClusterShell (tests only)
- VTK (more than tests?)

For the first two, the respective upstreams have fixes by now. For VTK all I now is what can be read in:
- #840
- https://gitlab.kitware.com/vtk/vtk/-/issues/19258

I believe there is nothing more to do about this at Expat upstream. What is your understanding of the situation?

**Comment by Snild-Sony** [comment]
I agree.

I would be interested to know if my suggestion in https://gitlab.kitware.com/vtk/vtk/-/issues/19258 works. Maybe they've tried and it didn't? You're more experienced with expat's API; do you think the idea should work?

**Comment by hartwork** [comment]
@Snild-Sony I haven't had a chance at a closer look yet. VTK has not replied to your comment for a month now, I think I will wait for their next reply before a closer look, for a few more days at least. Seemed interesting for sure, but I'll need to watch my battery a bit this week.

**Comment by Snild-Sony** [comment]
Understood. Take care.

**Comment by hartwork** [comment]
> What is your understanding of the situation?

@soluwalana I haven't heard back in a week and I consider this answered and "nothing more to do upstream". I'll close but we can sure re-open if the picture is missing something. Closing…
