### ISSUE TITLE
CMake: case for package name (expat or EXPAT)

### ISSUE THREAD

**Issue by chemodax** [libexpat/libexpat#858]
Currently CMakeLists.txt uses lowercase name for package name and exported namespace (expat):
https://github.com/libexpat/libexpat/blob/e48ab6604f04ee71f311b3e8170379b48ce77c2b/expat/CMakeLists.txt#L877

While standard [FindEXPAT()](https://cmake.org/cmake/help/latest/module/FindEXPAT.html) and find_package(EXPAT) uses uppercase name (EXPAT) for package name and exported namespace.

This introduce different problems when consuming Expat via CMake.

It would be very nice to synchronize package names in CMakeLists.txt and FindEXPAT().

**Comment by hartwork** [comment]
@chemodax I expected more problems from uniting the two because (1) the behavior is not identical and (2) build systems that currently use "expat" lowercase would break. Also, https://github.com/libexpat/libexpat?tab=readme-ov-file#using-libexpat-in-your-cmake-based-project documents the behavior. I'll close this as wontfix. Thanks for your understanding.

**Comment by chemodax** [comment]
Ok, thanks!
