### ISSUE TITLE
Please consider signing all your release files

### ISSUE THREAD

**Issue by sldr** [libexpat/libexpat#877]
From the download url (https://github.com/libexpat/libexpat/releases), I noticed that the 2 source distros were not signed along with the 2 Windows binary distro files. This is as of version 2.6.2 of libexpat.

To be clear, I mean signing with gpg/pgp like your Linux release files.

Thanks,
SLDR
(Stephen L. De Rudder)

**Comment by hartwork** [comment]
Hi @sldr,

the Windows binaries are not signed because AppVeyor CI generates them not me and I cannot sign something that I did not produce.

For the source files, the only downloads without signatures are the ones auto-generated by GitHub…

![binaries_Screenshot_20240627_230118](https://github.com/libexpat/libexpat/assets/1577132/c7575c2d-7368-43d2-938f-dbc224162325)

…where the Git tag pointing to the related commit is signed.

A full release already takes multiple hours to do — see #838 for the steps involved — and signing those two would mean I download the two from GitHub and do validation of their contain against the related commit in a way that anyone else could do with the same level of trust in outcome.

Could you help me understand your build pipeline or environment better to understand how both (a) the signed release tarballs and (b) checking out the release tag and verifying the commit signature do not work for you or your environment? I'd be happy to understand.

Thanks! :beers:

**Comment by sldr** [comment]
OK, the Windows kits was more of a nice to have. We wouldn't use them anyway since we build from sources. I can understand not wanting to sign CI builds that were generated on a machine you don't fully control. FYI: The MS Defender anti-virus didn't like the Windows binary zip file for some reason.

As far as the source distros, you bring up a good point. I can clone the repo and use the tag to checkout the source (and verify you created the tag). I will definitely do this and thanks for pointing it out. However, I think it would be nice if you would take the time to verify the 2 source repos and sign them. Just think, that your extra hour (swag) spent signing will be a time savings multiplied by every user that verifies the source download. 😀 I know; users are always wanting more. 🤣

Thank you (and everyone else that has helped) for the time and effort you all put into this so that we and many others can benefit.

As far as our build pipeline; we take a specific version of libexpat source and put it into our repo and then build everything from that repo (libexpat, our stuff, etc on Windows and Linux). Just recently, I have been moving to multiple repos (with clones) and doing submodules in the main repo that point to the local cloned repo. This allows us to modify libexpat source if we needed to (and we haven't needed to for libexpat) and keep the modifications with newer versions of libexpat. I haven't created a libexpat cloned repo yet, but it is on the todo list.

PS: Yes, I do see that doing my todo list, kinda solves the signing issue...
PSS: Ok, Ok, Ok, yes, the "word" 'kinda' could be removed from above... 😉

Laters,
SLDR

**Comment by hartwork** [comment]
@sldr thanks for elaborating. I don't really see me adding that step to the manual release process at the moment, I will close the issue as "good enough" for now. Thanks for your understanding, have a nice weekend! :pray:

**Comment by sldr** [comment]
Thank you, and you have a great weekend too!
