### ISSUE TITLE
[>=2.6.0] Event handler call is delayed in some cases?

### ISSUE THREAD

**Issue by pointsman** [libexpat/libexpat#895]
The observed mis-behaviour is illustrated by this programm:

```
#include <expat.h>
#include <stdio.h>
#include <string.h>

static void
elementStart (void *userData, const char *name, const char **atts)
{
    fprintf (stderr, "elementStart called for element %s\n", name);
}

#define PARSE_CHUNK_SIZE 1

int
main (int argc, char **argv) 
{
    XML_Parser parser;
    enum XML_Status result;
    char *data = "<doc><elm/></doc>";
    int done, len = strlen (data);
    
    parser = XML_ParserCreate(NULL);
    XML_SetElementHandler(parser, elementStart, NULL);
    
    do {
        done = (len < PARSE_CHUNK_SIZE);
        fprintf (stderr, "parsing '%c'\n", *data);
        result = XML_Parse(parser, data,
                           done ? len : PARSE_CHUNK_SIZE,
                           done ? 1 : 0);
        if (!done) {
            data += PARSE_CHUNK_SIZE;
            len -= PARSE_CHUNK_SIZE;
        }
    } while (!done && result == XML_STATUS_OK);
    XML_ParserFree (parser);

    return 0;
}

````
Build and linked with expat 2.6.2 this example programm outputs for me:

```
parsing '<'
parsing 'd'
parsing 'o'
parsing 'c'
parsing '>'
parsing '<'
parsing 'e'
parsing 'l'
elementStart called for element doc
parsing 'm'
parsing '/'
parsing '>'
parsing '<'
parsing '/'
elementStart called for element elm
parsing 'd'
parsing 'o'
parsing 'c'
parsing '>'
parsing ''

```
Please note that the element start handler for the document element is only called after the parser already has parsed the first 3 characters of the first child element tag. In similar way see that the element start handler call for the first child element (elm) is only called after the parser has already parsed the first two characters of the closing document element tag.

This is a regression (or at least a behaviour change, but then I haven't found a note about this changed behaviour in the release notes) to earlier versions and was apparently introduced with expat 2.5.0. If I link the example program from above with expat 2.4.9 I get:

```
parsing '<'
parsing 'd'
parsing 'o'
parsing 'c'
parsing '>'
elementStart called for element doc
parsing '<'
parsing 'e'
parsing 'l'
parsing 'm'
parsing '/'
parsing '>'
elementStart called for element elm
parsing '<'
parsing '/'
parsing 'd'
parsing 'o'
parsing 'c'
parsing '>'
parsing ''
```

This is the result / behaviour I would also expect from current expat versions.

Please note that the key to trigger this regression is not the somewhat ridiculous small (1 byte) chunk size. This late delivering of event handler calls can be demonstrated with any parsing chunk size. The key seems to be that the chunk size is smaller than the length of the parsed tag.

**Comment by hartwork** [comment]
@pointsman this is expected behavior for Expat >=2.**6**.0 from pull request #789 to address a related security issue. If you want the *old and insecure* behavior you can call API function [`XML_SetReparseDeferralEnabled`](https://libexpat.github.io/doc/api/latest/#XML_SetReparseDeferralEnabled). Does that answer the question?

CC @Snild-Sony

**Comment by hartwork** [comment]
@pointsman PS: Here's the minimal patch needed to your example:

```diff
--- a/main.c
+++ b/main.c
@@ -19,6 +19,7 @@ main (int argc, char **argv)
     int done, len = strlen (data);
     
     parser = XML_ParserCreate(NULL);
+    XML_SetReparseDeferralEnabled(parser, XML_FALSE);
     XML_SetElementHandler(parser, elementStart, NULL);
     
     do {
```

I confirmed that it does restore the behavior you asked for.

Does that answer the question?

**Comment by pointsman** [comment]
Well, OK, I kind of see ... (the documentation for XML_SetReparseDeferralEnabled() does not really spell out what consquences the default has, btw.)

Not sure, if I fully agree, though. The security risk is that without this a DOS attack is a bit easier, yes?
It still should be possible to bring an expat using app/service to its knees with an endless tag name, though.

And for this we have "unpredictical behaviour" - the event handler is not always called as (early as) expected.

The current default means to kick the problem down the road, to the application which uses expat. If an application depends on that the events are reliable reported in time then it has to use explicitely XML_SetReparseDeferralEnabled() (and the programmer must therefor be aware of it).

Ideal would be to have both: no quadratic behaviour while parsing looong tokens and event delivery in time. I understand this not easy possible. I only (mildly) question that this is enabled by default.

**Comment by hartwork** [comment]
@pointsman the default has to be enabled because "secure by default". We definitely accept pull requests against the documenation to make things more clear. If you do find ways to practically bring Expat "to its knees with an endless tag name" as you said, that would be a security issue and a report with a reproducer and a fixing pull request will be welcome.

**Comment by Snild-Sony** [comment]
> It still should be possible to bring an expat using app/service to its knees with an endless tag name, though.

In that it will use up a lot of memory and CPU? Yes, of course -- but as far as I'm aware, it will be _linear_ with the input size, and therefore easy to avoid by setting input size limits in the application.

In contrast, the old parsing behavior could be quadratic time, so even a fairly small input could cost a lot of CPU. It was also impossible to tell ahead of time if a certain input would trigger this behavior or not (without building another parser to check for it).

> The key seems to be that the chunk size is smaller than the length of the parsed tag.

That is correct. Specifically, the "defer" heuristic triggers when an attempt to parse the pending input data fails to output any result at all (because more input is needed).

> Ideal would be to have both: no quadratic behaviour while parsing looong tokens and event delivery in time.

I agree. Unfortunately, as far as @hartwork and I could tell, this is not possible without redesigning expat essentially from scratch. As the readme and [Changes](https://github.com/libexpat/libexpat/blob/master/expat/Changes) file notes, expat is understaffed and without funding.

> If an application depends on that the events are reliable reported in time then it has to use explicitely XML_SetReparseDeferralEnabled() (and the programmer must therefor be aware of it).

I think awareness is a good thing.

-------------

IIRC, `XML_SetReparseDeferralEnabled()` can be switched on and off dynamically. If it suits your situation, you could disable it at key points (e.g. when a stream temporarily runs out of data), then re-enable it. This requires careful analysis on the application side -- for example, it would not protect against someone sending 10MB of data, then multiple 1-byte increments -- but it _could_ be an acceptable compromise depending on your situation.
